train_data_dir: "E:/pages/InvMIHNet-master/InvMIHNet-master/datasets/DIV2K_train_HR"
val_data_dir: "E:/pages/InvMIHNet-master/InvMIHNet-master/datasets/DIV2K_valid_HR"
train_size: 8000
val_size: 2000
epochs: 50
batch_size: 16
warmup_epochs: 10
adv_start_epoch: 10
w_pixel: 0.01
w_feat: 0.001
w_extract: 1000.0
w_adv: 0.0
eval_every: 5
threshold: 0.5
